"""add_delay_model

Revision ID: 8bee876b232d
Revises: 2e53cf4e01c2
Create Date: 2026-09-03 10:11:00.169599

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8bee876b232d'
down_revision = '2e53cf4e01c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('delays',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('centre_id', sa.Integer(), nullable=False),
    sa.Column('slot_id', sa.Integer(), nullable=True),
    sa.Column('delay_date', sa.Date(), nullable=False),
    sa.Column('delay_minutes', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['centre_id'], ['centres.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['slot_id'], ['slots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('delays', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_delays_centre_id'), ['centre_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_delays_delay_date'), ['delay_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_delays_slot_id'), ['slot_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_delays_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('delays', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_delays_status'))
        batch_op.drop_index(batch_op.f('ix_delays_slot_id'))
        batch_op.drop_index(batch_op.f('ix_delays_delay_date'))
        batch_op.drop_index(batch_op.f('ix_delays_centre_id'))

    op.drop_table('delays')
    # ### end Alembic commands ###
